drop extension if exists "pg_net";
create schema if not exists "api";
create extension if not exists "vector" with schema "public";
create table "public"."applications" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "company" text not null,
    "date_applied" date,
    "status" text not null default 'Ready To Apply'::text,
    "position" text not null,
    "location" text not null,
    "resume_filename" text,
    "resume_path" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "source_resume_run_id" uuid
      );
alter table "public"."applications" enable row level security;
create table "public"."documents" (
    "id" uuid not null default gen_random_uuid(),
    "raw_text" text not null,
    "role_slug" text not null,
    "metadata" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );
alter table "public"."documents" enable row level security;
create table "public"."embeddings" (
    "id" bigint generated by default as identity not null,
    "document_id" uuid not null,
    "chunk_index" integer not null default 0,
    "chunk_text" text not null,
    "embedding" public.vector(1536),
    "metadata" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default now()
      );
alter table "public"."embeddings" enable row level security;
create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "full_name" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "job_role" text
      );
alter table "public"."profiles" enable row level security;
create table "public"."resume_documents" (
    "id" uuid not null default gen_random_uuid(),
    "run_id" uuid not null,
    "user_id" uuid not null,
    "resume_path" text not null,
    "text" text not null,
    "text_source" text not null default 'extract_service'::text,
    "chars" integer not null default 0,
    "metadata" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );
alter table "public"."resume_documents" enable row level security;
create table "public"."resume_runs" (
    "id" uuid not null default gen_random_uuid(),
    "request_id" uuid not null,
    "user_id" uuid not null,
    "resume_path" text not null,
    "resume_filename" text,
    "job_description" text not null,
    "status" text not null default 'queued'::text,
    "error_code" text,
    "error_message" text,
    "output" jsonb,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );
alter table "public"."resume_runs" enable row level security;
create table "public"."roles" (
    "slug" text not null,
    "label" text not null,
    "created_at" timestamp with time zone not null default now()
      );
alter table "public"."roles" enable row level security;
create table "public"."user_job_roles" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "job_role" text not null,
    "created_at" timestamp with time zone not null default now()
      );
alter table "public"."user_job_roles" enable row level security;
CREATE UNIQUE INDEX applications_pkey ON public.applications USING btree (id);
CREATE UNIQUE INDEX applications_source_resume_run_id_key ON public.applications USING btree (source_resume_run_id);
CREATE UNIQUE INDEX documents_pkey ON public.documents USING btree (id);
CREATE INDEX documents_role_slug_idx ON public.documents USING btree (role_slug);
CREATE UNIQUE INDEX embeddings_document_chunk_unique ON public.embeddings USING btree (document_id, chunk_index);
CREATE INDEX embeddings_document_id_idx ON public.embeddings USING btree (document_id);
CREATE UNIQUE INDEX embeddings_pkey ON public.embeddings USING btree (id);
CREATE INDEX idx_applications_user_date_applied ON public.applications USING btree (user_id, date_applied DESC);
CREATE INDEX idx_applications_user_id ON public.applications USING btree (user_id);
CREATE INDEX idx_applications_user_status ON public.applications USING btree (user_id, status);
CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);
CREATE UNIQUE INDEX resume_documents_pkey ON public.resume_documents USING btree (id);
CREATE INDEX resume_documents_resume_path_idx ON public.resume_documents USING btree (resume_path);
CREATE INDEX resume_documents_run_id_idx ON public.resume_documents USING btree (run_id);
CREATE UNIQUE INDEX resume_documents_run_id_key ON public.resume_documents USING btree (run_id);
CREATE INDEX resume_documents_user_id_idx ON public.resume_documents USING btree (user_id);
CREATE UNIQUE INDEX resume_runs_pkey ON public.resume_runs USING btree (id);
CREATE UNIQUE INDEX resume_runs_request_id_key ON public.resume_runs USING btree (request_id);
CREATE INDEX resume_runs_status_idx ON public.resume_runs USING btree (status);
CREATE INDEX resume_runs_user_id_created_at_idx ON public.resume_runs USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX resume_runs_user_id_request_id_uidx ON public.resume_runs USING btree (user_id, request_id);
CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (slug);
CREATE UNIQUE INDEX user_job_roles_pkey ON public.user_job_roles USING btree (id);
alter table "public"."applications" add constraint "applications_pkey" PRIMARY KEY using index "applications_pkey";
alter table "public"."documents" add constraint "documents_pkey" PRIMARY KEY using index "documents_pkey";
alter table "public"."embeddings" add constraint "embeddings_pkey" PRIMARY KEY using index "embeddings_pkey";
alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";
alter table "public"."resume_documents" add constraint "resume_documents_pkey" PRIMARY KEY using index "resume_documents_pkey";
alter table "public"."resume_runs" add constraint "resume_runs_pkey" PRIMARY KEY using index "resume_runs_pkey";
alter table "public"."roles" add constraint "roles_pkey" PRIMARY KEY using index "roles_pkey";
alter table "public"."user_job_roles" add constraint "user_job_roles_pkey" PRIMARY KEY using index "user_job_roles_pkey";
alter table "public"."applications" add constraint "applications_source_resume_run_id_fkey" FOREIGN KEY (source_resume_run_id) REFERENCES public.resume_runs(id) ON DELETE CASCADE not valid;
alter table "public"."applications" validate constraint "applications_source_resume_run_id_fkey";
alter table "public"."applications" add constraint "applications_source_resume_run_id_key" UNIQUE using index "applications_source_resume_run_id_key";
alter table "public"."applications" add constraint "applications_status_check" CHECK ((status = ANY (ARRAY['Applied'::text, 'Interview #1'::text, 'Interview #2'::text, 'Rejected'::text, 'Ready To Apply'::text]))) not valid;
alter table "public"."applications" validate constraint "applications_status_check";
alter table "public"."applications" add constraint "applications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."applications" validate constraint "applications_user_id_fkey";
alter table "public"."documents" add constraint "documents_role_slug_fkey" FOREIGN KEY (role_slug) REFERENCES public.roles(slug) ON UPDATE CASCADE not valid;
alter table "public"."documents" validate constraint "documents_role_slug_fkey";
alter table "public"."embeddings" add constraint "embeddings_document_chunk_unique" UNIQUE using index "embeddings_document_chunk_unique";
alter table "public"."embeddings" add constraint "embeddings_document_id_fkey" FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE not valid;
alter table "public"."embeddings" validate constraint "embeddings_document_id_fkey";
alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."profiles" validate constraint "profiles_id_fkey";
alter table "public"."resume_documents" add constraint "resume_documents_run_id_fkey" FOREIGN KEY (run_id) REFERENCES public.resume_runs(id) ON DELETE CASCADE not valid;
alter table "public"."resume_documents" validate constraint "resume_documents_run_id_fkey";
alter table "public"."resume_documents" add constraint "resume_documents_run_id_key" UNIQUE using index "resume_documents_run_id_key";
alter table "public"."resume_documents" add constraint "resume_documents_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."resume_documents" validate constraint "resume_documents_user_id_fkey";
alter table "public"."resume_runs" add constraint "resume_runs_request_id_key" UNIQUE using index "resume_runs_request_id_key";
alter table "public"."resume_runs" add constraint "resume_runs_status_check" CHECK ((status = ANY (ARRAY['queued'::text, 'extracting'::text, 'extracted'::text, 'failed'::text]))) not valid;
alter table "public"."resume_runs" validate constraint "resume_runs_status_check";
alter table "public"."resume_runs" add constraint "resume_runs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;
alter table "public"."resume_runs" validate constraint "resume_runs_user_id_fkey";
alter table "public"."roles" add constraint "roles_slug_format" CHECK ((slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'::text)) not valid;
alter table "public"."roles" validate constraint "roles_slug_format";
alter table "public"."user_job_roles" add constraint "user_job_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;
alter table "public"."user_job_roles" validate constraint "user_job_roles_user_id_fkey";
set check_function_bodies = off;
CREATE OR REPLACE FUNCTION public.create_application_from_resume_run()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.applications (
    source_resume_run_id,
    user_id,
    company,
    date_applied,
    status,
    position,
    location,
    resume_filename,
    resume_path
  )
  values (
    new.id,
    new.user_id,
    'TBD',
    null,
    'Ready To Apply',
    'TBD',
    'TBD',
    new.resume_filename,
    new.resume_path
  )
  on conflict (source_resume_run_id) do update
  set
    resume_filename = excluded.resume_filename,
    resume_path = excluded.resume_path,
    user_id = excluded.user_id;

  return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.enforce_resume_documents_matches_run()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  run_owner uuid;
  run_path text;
begin
  select rr.user_id, rr.resume_path
    into run_owner, run_path
  from public.resume_runs rr
  where rr.id = new.run_id;

  if run_owner is null then
    raise exception 'resume_runs row not found for run_id=%', new.run_id;
  end if;

  if new.user_id <> run_owner then
    raise exception 'user_id must match resume_runs.user_id for run_id=%', new.run_id;
  end if;

  if new.resume_path <> run_path then
    raise exception 'resume_path must match resume_runs.resume_path for run_id=%', new.run_id;
  end if;

  new.chars := coalesce(char_length(new.text), 0);
  return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.enforce_resume_runs_insert_queued()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  -- Extraction lifecycle must start from queued on insert.
  new.status := 'queued';
  new.error_code := null;
  new.error_message := null;
  return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  insert into public.profiles (
    id,
    email,
    full_name,
    job_role
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    new.raw_user_meta_data->>'job_role'
  );

  return new;
end;
$function$;
CREATE OR REPLACE FUNCTION public.match_embeddings(query_embedding text, match_count integer DEFAULT 5, role_slug_filter text DEFAULT NULL::text)
 RETURNS TABLE(id bigint, document_id uuid, chunk_index integer, chunk_text text, similarity double precision, metadata jsonb)
 LANGUAGE sql
 STABLE
AS $function$
  select
    e.id,
    e.document_id,
    e.chunk_index,
    e.chunk_text,
    1 - (e.embedding <=> (query_embedding::vector)) as similarity,
    e.metadata
  from public.embeddings e
  join public.documents d on d.id = e.document_id
  where role_slug_filter is null or d.role_slug = role_slug_filter
  order by e.embedding <=> (query_embedding::vector)
  limit greatest(match_count, 1);
$function$;
CREATE OR REPLACE FUNCTION public.match_embeddings(query_embedding text, role_slug_filter text, match_count integer DEFAULT 5, source_type_filter text DEFAULT NULL::text, document_type_filter text DEFAULT NULL::text)
 RETURNS TABLE(id bigint, document_id uuid, chunk_index integer, chunk_text text, similarity double precision, metadata jsonb)
 LANGUAGE sql
 STABLE
AS $function$
  select
    e.id,
    e.document_id,
    e.chunk_index,
    e.chunk_text,
    1 - (e.embedding <=> (query_embedding::vector)) as similarity,
    e.metadata
  from public.embeddings e
  join public.documents d on d.id = e.document_id
  where d.role_slug = role_slug_filter
    and (
      source_type_filter is null
      or d.metadata ->> 'source_type' = source_type_filter
    )
    and (
      document_type_filter is null
      or d.metadata ->> 'document_type' = document_type_filter
    )
  order by e.embedding <=> (query_embedding::vector)
  limit greatest(match_count, 1);
$function$;
CREATE OR REPLACE FUNCTION public.match_embeddings(query_embedding text, role_slug_filter text, user_id_filter text, match_count integer DEFAULT 5, source_type_filter text DEFAULT NULL::text, document_type_filter text DEFAULT NULL::text)
 RETURNS TABLE(id bigint, document_id uuid, chunk_index integer, chunk_text text, similarity double precision, metadata jsonb)
 LANGUAGE sql
 STABLE
AS $function$
  select
    e.id,
    e.document_id,
    e.chunk_index,
    e.chunk_text,
    1 - (e.embedding <=> (query_embedding::vector)) as similarity,
    e.metadata
  from public.embeddings e
  join public.documents d on d.id = e.document_id
  where d.role_slug = role_slug_filter
    and d.metadata ->> 'user_id' = user_id_filter
    and (
      source_type_filter is null
      or d.metadata ->> 'source_type' = source_type_filter
    )
    and (
      document_type_filter is null
      or d.metadata ->> 'document_type' = document_type_filter
    )
  order by e.embedding <=> (query_embedding::vector)
  limit greatest(match_count, 1);
$function$;
CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;
grant delete on table "public"."applications" to "anon";
grant insert on table "public"."applications" to "anon";
grant references on table "public"."applications" to "anon";
grant select on table "public"."applications" to "anon";
grant trigger on table "public"."applications" to "anon";
grant truncate on table "public"."applications" to "anon";
grant update on table "public"."applications" to "anon";
grant delete on table "public"."applications" to "authenticated";
grant insert on table "public"."applications" to "authenticated";
grant references on table "public"."applications" to "authenticated";
grant select on table "public"."applications" to "authenticated";
grant trigger on table "public"."applications" to "authenticated";
grant truncate on table "public"."applications" to "authenticated";
grant update on table "public"."applications" to "authenticated";
grant delete on table "public"."applications" to "service_role";
grant insert on table "public"."applications" to "service_role";
grant references on table "public"."applications" to "service_role";
grant select on table "public"."applications" to "service_role";
grant trigger on table "public"."applications" to "service_role";
grant truncate on table "public"."applications" to "service_role";
grant update on table "public"."applications" to "service_role";
grant delete on table "public"."documents" to "service_role";
grant insert on table "public"."documents" to "service_role";
grant references on table "public"."documents" to "service_role";
grant select on table "public"."documents" to "service_role";
grant trigger on table "public"."documents" to "service_role";
grant truncate on table "public"."documents" to "service_role";
grant update on table "public"."documents" to "service_role";
grant delete on table "public"."embeddings" to "service_role";
grant insert on table "public"."embeddings" to "service_role";
grant references on table "public"."embeddings" to "service_role";
grant select on table "public"."embeddings" to "service_role";
grant trigger on table "public"."embeddings" to "service_role";
grant truncate on table "public"."embeddings" to "service_role";
grant update on table "public"."embeddings" to "service_role";
grant delete on table "public"."profiles" to "anon";
grant insert on table "public"."profiles" to "anon";
grant references on table "public"."profiles" to "anon";
grant select on table "public"."profiles" to "anon";
grant trigger on table "public"."profiles" to "anon";
grant truncate on table "public"."profiles" to "anon";
grant update on table "public"."profiles" to "anon";
grant delete on table "public"."profiles" to "authenticated";
grant insert on table "public"."profiles" to "authenticated";
grant references on table "public"."profiles" to "authenticated";
grant select on table "public"."profiles" to "authenticated";
grant trigger on table "public"."profiles" to "authenticated";
grant truncate on table "public"."profiles" to "authenticated";
grant update on table "public"."profiles" to "authenticated";
grant delete on table "public"."profiles" to "service_role";
grant insert on table "public"."profiles" to "service_role";
grant references on table "public"."profiles" to "service_role";
grant select on table "public"."profiles" to "service_role";
grant trigger on table "public"."profiles" to "service_role";
grant truncate on table "public"."profiles" to "service_role";
grant update on table "public"."profiles" to "service_role";
grant delete on table "public"."resume_documents" to "anon";
grant insert on table "public"."resume_documents" to "anon";
grant references on table "public"."resume_documents" to "anon";
grant select on table "public"."resume_documents" to "anon";
grant trigger on table "public"."resume_documents" to "anon";
grant truncate on table "public"."resume_documents" to "anon";
grant update on table "public"."resume_documents" to "anon";
grant delete on table "public"."resume_documents" to "authenticated";
grant insert on table "public"."resume_documents" to "authenticated";
grant references on table "public"."resume_documents" to "authenticated";
grant select on table "public"."resume_documents" to "authenticated";
grant trigger on table "public"."resume_documents" to "authenticated";
grant truncate on table "public"."resume_documents" to "authenticated";
grant update on table "public"."resume_documents" to "authenticated";
grant delete on table "public"."resume_documents" to "service_role";
grant insert on table "public"."resume_documents" to "service_role";
grant references on table "public"."resume_documents" to "service_role";
grant select on table "public"."resume_documents" to "service_role";
grant trigger on table "public"."resume_documents" to "service_role";
grant truncate on table "public"."resume_documents" to "service_role";
grant update on table "public"."resume_documents" to "service_role";
grant delete on table "public"."resume_runs" to "anon";
grant insert on table "public"."resume_runs" to "anon";
grant references on table "public"."resume_runs" to "anon";
grant select on table "public"."resume_runs" to "anon";
grant trigger on table "public"."resume_runs" to "anon";
grant truncate on table "public"."resume_runs" to "anon";
grant update on table "public"."resume_runs" to "anon";
grant delete on table "public"."resume_runs" to "authenticated";
grant insert on table "public"."resume_runs" to "authenticated";
grant references on table "public"."resume_runs" to "authenticated";
grant select on table "public"."resume_runs" to "authenticated";
grant trigger on table "public"."resume_runs" to "authenticated";
grant truncate on table "public"."resume_runs" to "authenticated";
grant update on table "public"."resume_runs" to "authenticated";
grant delete on table "public"."resume_runs" to "service_role";
grant insert on table "public"."resume_runs" to "service_role";
grant references on table "public"."resume_runs" to "service_role";
grant select on table "public"."resume_runs" to "service_role";
grant trigger on table "public"."resume_runs" to "service_role";
grant truncate on table "public"."resume_runs" to "service_role";
grant update on table "public"."resume_runs" to "service_role";
grant select on table "public"."roles" to "authenticated";
grant delete on table "public"."roles" to "service_role";
grant insert on table "public"."roles" to "service_role";
grant references on table "public"."roles" to "service_role";
grant select on table "public"."roles" to "service_role";
grant trigger on table "public"."roles" to "service_role";
grant truncate on table "public"."roles" to "service_role";
grant update on table "public"."roles" to "service_role";
grant delete on table "public"."user_job_roles" to "anon";
grant insert on table "public"."user_job_roles" to "anon";
grant references on table "public"."user_job_roles" to "anon";
grant select on table "public"."user_job_roles" to "anon";
grant trigger on table "public"."user_job_roles" to "anon";
grant truncate on table "public"."user_job_roles" to "anon";
grant update on table "public"."user_job_roles" to "anon";
grant delete on table "public"."user_job_roles" to "authenticated";
grant insert on table "public"."user_job_roles" to "authenticated";
grant references on table "public"."user_job_roles" to "authenticated";
grant select on table "public"."user_job_roles" to "authenticated";
grant trigger on table "public"."user_job_roles" to "authenticated";
grant truncate on table "public"."user_job_roles" to "authenticated";
grant update on table "public"."user_job_roles" to "authenticated";
grant delete on table "public"."user_job_roles" to "service_role";
grant insert on table "public"."user_job_roles" to "service_role";
grant references on table "public"."user_job_roles" to "service_role";
grant select on table "public"."user_job_roles" to "service_role";
grant trigger on table "public"."user_job_roles" to "service_role";
grant truncate on table "public"."user_job_roles" to "service_role";
grant update on table "public"."user_job_roles" to "service_role";
create policy "applications_delete_own"
  on "public"."applications"
  as permissive
  for delete
  to authenticated
using ((user_id = auth.uid()));
create policy "applications_insert_own"
  on "public"."applications"
  as permissive
  for insert
  to authenticated
with check ((user_id = auth.uid()));
create policy "applications_select_own"
  on "public"."applications"
  as permissive
  for select
  to authenticated
using ((user_id = auth.uid()));
create policy "applications_update_own"
  on "public"."applications"
  as permissive
  for update
  to authenticated
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));
create policy "documents_service_role_all"
  on "public"."documents"
  as permissive
  for all
  to service_role
using (true)
with check (true);
create policy "embeddings_service_role_all"
  on "public"."embeddings"
  as permissive
  for all
  to service_role
using (true)
with check (true);
create policy "profiles_insert_own"
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((auth.uid() = id));
create policy "profiles_select_own"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));
create policy "profiles_update_own"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id))
with check ((auth.uid() = id));
create policy "resume_documents_delete_own"
  on "public"."resume_documents"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));
create policy "resume_documents_insert_own"
  on "public"."resume_documents"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));
create policy "resume_documents_select_own"
  on "public"."resume_documents"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));
create policy "resume_documents_update_own"
  on "public"."resume_documents"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));
create policy "resume_runs_delete_own"
  on "public"."resume_runs"
  as permissive
  for delete
  to authenticated
using ((user_id = auth.uid()));
create policy "resume_runs_insert_own"
  on "public"."resume_runs"
  as permissive
  for insert
  to authenticated
with check ((user_id = auth.uid()));
create policy "resume_runs_select_own"
  on "public"."resume_runs"
  as permissive
  for select
  to authenticated
using ((user_id = auth.uid()));
create policy "resume_runs_update_own"
  on "public"."resume_runs"
  as permissive
  for update
  to authenticated
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));
create policy "roles_read_authenticated"
  on "public"."roles"
  as permissive
  for select
  to authenticated
using (true);
create policy "roles_delete_own"
  on "public"."user_job_roles"
  as permissive
  for delete
  to public
using ((auth.uid() = user_id));
create policy "roles_insert_own"
  on "public"."user_job_roles"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id));
create policy "roles_select_own"
  on "public"."user_job_roles"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));
CREATE TRIGGER trg_applications_set_updated_at BEFORE UPDATE ON public.applications FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_documents_set_updated_at BEFORE UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_enforce_resume_documents_matches_run BEFORE INSERT OR UPDATE ON public.resume_documents FOR EACH ROW EXECUTE FUNCTION public.enforce_resume_documents_matches_run();
CREATE TRIGGER trg_resume_documents_set_updated_at BEFORE UPDATE ON public.resume_documents FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER set_resume_runs_updated_at BEFORE UPDATE ON public.resume_runs FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_create_application_from_resume_run AFTER INSERT ON public.resume_runs FOR EACH ROW EXECUTE FUNCTION public.create_application_from_resume_run();
CREATE TRIGGER trg_enforce_resume_runs_insert_queued BEFORE INSERT ON public.resume_runs FOR EACH ROW EXECUTE FUNCTION public.enforce_resume_runs_insert_queued();
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
create policy "resume_read_own_folder"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'Resumes'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
create policy "resume_upload_own_folder"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'Resumes'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
create policy "resumes_delete_own_files"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'resumes'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
create policy "resumes_read_own_files"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'resumes'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
create policy "resumes_upload_own_folder"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'resumes'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
